package models

import "time"

// BrandProfile defines the identity and voice of the company agent.
type BrandProfile struct {
	ID                    string   `json:"id"`
	Name                  string   `json:"name"`
	Industry              string   `json:"industry"`
	Voice                 string   `json:"voice"`                   // e.g. "Professional", "Witty"
	TargetAudience        string   `json:"target_audience"`         // e.g. "CTOs", "Gen Z"
	Topics                []string `json:"topics"`                  // e.g. ["AI", "Cloud"]
	AntiTopics            []string `json:"anti_topics"`             // e.g. ["Politics"]
	ScheduleIntervalHours int      `json:"schedule_interval_hours"` // e.g. 4
}

// Trend represents a potential topic discovered during research.
type Trend struct {
	Query     string    `json:"query"`
	Title     string    `json:"title"`
	Snippet   string    `json:"snippet"`
	URL       string    `json:"url"`
	Timestamp time.Time `json:"timestamp"`
}

// PostStatus defines the lifecycle of a post.
type PostStatus string

const (
	StatusDraft     PostStatus = "draft"
	StatusPending   PostStatus = "pending_review"
	StatusApproved  PostStatus = "approved"
	StatusScheduled PostStatus = "scheduled"
	StatusPublished PostStatus = "published"
	StatusFailed    PostStatus = "failed"
)

type ScheduledPost struct {
	ID          string     `json:"id"`
	BrandID     string     `json:"brand_id"`
	Topic       string     `json:"topic"`
	Content     string     `json:"content"`
	Platform    string     `json:"platform"`
	Status      PostStatus `json:"status"`
	ScheduledAt time.Time  `json:"scheduled_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

// Post represents a piece of content generated by the agent.
type Post struct {
	ID        string     `json:"id"`
	SocialID  string     `json:"social_id"` // Platform-specific ID (Tweet ID, LinkedIn URN)
	BrandID   string     `json:"brand_id"`
	Topic     string     `json:"topic"`
	Content   string     `json:"content"`
	Platform  string     `json:"platform"` // e.g. "twitter", "linkedin"
	Status    PostStatus `json:"status"`
	Analytics Analytics  `json:"analytics"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// Analytics holds performance data for a post.
type Analytics struct {
	Views    int `json:"views"`
	Likes    int `json:"likes"`
	Shares   int `json:"shares"`
	Comments int `json:"comments"`
}

// AgentState tracks the current context of the agent loop.
type AgentState struct {
	CurrentBrand BrandProfile
	ActiveTrends []Trend
}
